
# This file is automatically generated, you probably don't want to edit this

ButtonsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ButtonsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            showSampleBtn = FALSE,
            makeSampleBtn = FALSE, ...) {

            super$initialize(
                package="Buttons",
                name="Buttons",
                requiresData=FALSE,
                ...)

            private$..showSampleBtn <- jmvcore::OptionAction$new(
                "showSampleBtn",
                showSampleBtn,
                default=FALSE)
            private$..makeSampleBtn <- jmvcore::OptionAction$new(
                "makeSampleBtn",
                makeSampleBtn,
                default=FALSE)

            self$.addOption(private$..showSampleBtn)
            self$.addOption(private$..makeSampleBtn)
        }),
    active = list(
        showSampleBtn = function() private$..showSampleBtn$value,
        makeSampleBtn = function() private$..makeSampleBtn$value),
    private = list(
        ..showSampleBtn = NA,
        ..makeSampleBtn = NA)
)

ButtonsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ButtonsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        graphPlot = function() private$.items[["graphPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Buttons Example")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Buttons Example"))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=600,
                height=360,
                visible=TRUE,
                renderFun=".plotGraph"))}))

ButtonsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ButtonsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Buttons",
                name = "Buttons",
                version = c(1,0,0),
                options = options,
                results = ButtonsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Buttons Example
#'
#' 
#' @param showSampleBtn .
#' @param makeSampleBtn .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
Buttons <- function(
    showSampleBtn = FALSE,
    makeSampleBtn = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Buttons requires jmvcore to be installed (restart may be required)")


    options <- ButtonsOptions$new(
        showSampleBtn = showSampleBtn,
        makeSampleBtn = makeSampleBtn)

    analysis <- ButtonsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

